### ISSUE TITLE
Jsonpath expression does not return the result in result pane after new UI change

### ISSUE THREAD

**Issue by avighub** [ashphy/jsonpath-online-evaluator#18]
Issue details:
Earlier before the UI change, while typing the json path expression in JSONPath Syntax box, it used to show the result instantly on the Evaluation Results pane.

Now it is not working the same way as it worked.
Workaround is  to click on the checkbox output path and then uncheck to see the result in  Evaluation Results pane.

![image](https://user-images.githubusercontent.com/25950003/80678129-f3bbe300-8ad7-11ea-9f1d-2d9836404b74.png)
(In the image above, I have updated the expression to lastName, but it still shows firstName

**Comment by ashphy** [comment]
Thank you for reporting!

**Comment by avighub** [comment]
Thank you so much for the quick fix.
it works fine like before.
