### ISSUE TITLE
Output in incorrect format

### ISSUE THREAD

**Issue by gregsdennis** [ashphy/jsonpath-online-evaluator#2]
First off, nice website!  It makes testing paths quite easy.

Goessner's post states that the output is supposed to be an array containing the results or `false` if no matches were found.

However, I see the logic in representing it the way you do.  Can there be an option to output in JSON?

**Comment by ashphy** [comment]
No options is provided. Because the output `false` is confusable with the matched result.

**Comment by gregsdennis** [comment]
If the matched result is `false` then it should appear in an array as `[false]`. The bare value (not in an array) indicates no matches.

**Comment by ashphy** [comment]
`return false` when no path is goessner's specification, not a JSONPath's.
In other implementations like a Jayway JsonPath may return an exception or null.

This is a playgroud, the result is interpreted by human. It should be easily understandable for the user who does not know the specific implementation.

**Comment by gregsdennis** [comment]
Didn't Goessner develop JSONPath?  Aside from his blog post, there is no official spec that I'm aware.

My point in raising the issue was that the JSON output *is* easier for me to read, especially if I'm trying to validate output from my evaluator.  I'm just asking for the option.
