### ISSUE TITLE
Filter bug

### ISSUE THREAD

**Issue by cielong** [ashphy/jsonpath-online-evaluator#28]
With the example data, 
```json
{
  "firstName": "John",
  "lastName" : "doe",
  "age"      : 26,
  "address"  : {
    "streetAddress": "naist street",
    "city"         : "Nara",
    "postalCode"   : "630-0192"
  },
  "phoneNumbers": [
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]
}
```

and with JSONPath query:
```
$..phoneNumbers[?(@.['type'])]
```
This seems like should return 
```json
[
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]
```
But it shows `Nothing matches`?

Did I miss anything?

**Comment by jpaquit** [comment]
Behaviour is as expected: https://goessner.net/articles/JsonPath/
Not a bug.

**Comment by cielong** [comment]
But it seems `$..phoneNumbers[?(@.type])]` return result while `$..phoneNumbers[?(@.['type'])]` do not, shouldn't the be the same according to the docs? 

> . or []  ->  child operator

Or for some unknown reason, the server does not reflect the JSONPath query I wrote.

**Comment by jpaquit** [comment]
**@.['type']** is no valid javascript ; you should either write **@.type**, either write **@['type']**
What is in between brackets is interpreted by underlying scripting language.
**@.['type']** generates error (have a look to the developer console), then it won't work ;)

**Comment by cielong** [comment]
I see. Thanks for the clarification.
