### ISSUE TITLE
dot for subscript?

### ISSUE THREAD

**Issue by srl295** [ashphy/jsonpath-online-evaluator#4]
:+1: on the website, thanks

The online demo seems to treat these as equivalent:

```
$.phoneNumbers.[1].type
$.phoneNumbers.[:1].type
$.phoneNumbers.1.type
```

It seems that http://goessner.net/articles/JsonPath/index.html#e2 does not mention the last case (using `.1` as an array subscript). Is this a bug or an feature?

**Comment by srl295** [comment]
according to https://jsonpath.curiousconcept.com the "flow communications" implementation also supports `.1` as array subscript.

**Comment by ashphy** [comment]
This site uses https://www.npmjs.com/package/JSONPath
The standards does not exists, therefore each implementations has some dialect.
