### ISSUE TITLE
How to traverse the json doc if one of the keys has forward slashes in it.

### ISSUE THREAD

**Issue by amarzavery** [ashphy/jsonpath-online-evaluator#5]
Big 👍 for the jsonpath.com website. It is indeed very useful.

I want to access the operationId, in the following json. The "paths" object has a key with slashes and I think that makes it confusing.

I thought,

`$.paths['/subscriptions/{subscriptionId}/providers/Microsoft.Storage/checkNameAvailability'].post.operationId` would work. But it does not. 

Can you provide some hint, what am I doing wrong over here?

```json5
{
  "swagger": "2.0",
  "paths": {
    "/subscriptions/{subscriptionId}/providers/Microsoft.Storage/checkNameAvailability": {
      "post": {
        "tags": [
          "StorageAccounts"
        ],
        "operationId": "StorageAccounts_CheckNameAvailability",
        "description": "Checks that the storage account name is valid and is not already in use.",
        "x-ms-examples": {
          "storageAccountCheckNameAvailability": {"$ref": "../examples/storageAccountCheckNameAvailability.json"}
        },
        "parameters": [
          {
            "name": "accountName",
            "in": "body",
            "required": true,
            "schema": {
            },
            "description": "The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only."
          },
          {
            "name": "accountName1",
            "in": "formData",
            "required": true,
            "schema": {
            },
            "description": "The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only."
          },
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "OK -- Operation to check the storage account name availability was successful.",
            "schema": {
              "$ref": "#/definitions/CheckNameAvailabilityResult"
            }
          }
        }
      }
    },
```

**Comment by omkarkhatavkar** [comment]
Looks like your JSON is invalid, I tried with correct JSON seems to be working  

`{
  "swagger": "2.0",
  "paths": {
    "/subscriptions/{subscriptionId}/providers/Microsoft.Storage/checkNameAvailability": {
      "post": {
        "tags": [
          "StorageAccounts"
        ],
        "operationId": "StorageAccounts_CheckNameAvailability",
        "description": "Checks that the storage account name is valid and is not already in use.",
        "x-ms-examples": {
          "storageAccountCheckNameAvailability": {"$ref": "../examples/storageAccountCheckNameAvailability.json"}
        },
        "parameters": [
          {
            "name": "accountName",
            "in": "body",
            "required": true,
            "schema": {
            },
            "description": "The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only."
          },
          {
            "name": "accountName1",
            "in": "formData",
            "required": true,
            "schema": {
            },
            "description": "The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only."
          },
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "OK -- Operation to check the storage account name availability was successful.",
            "schema": {
              "$ref": "#/definitions/CheckNameAvailabilityResult"
            }
          }
        }
      }
    }
  }
  }`
