### ISSUE TITLE
while trying to put complex jsonpath when you enter "(" the page reloads and the entered contents are lost

### ISSUE THREAD

**Issue by SnehalTayade** [ashphy/jsonpath-online-evaluator#57]
trying to put jsonpath like - $.[?(@.name=='PRODUCTPRICING')].serviceOrders[0].lastUpdated

as soon as you enter first round opening brace like ( the page reloads and the contents as in the request payload is lost

**Comment by mjmatthiesen** [comment]
It isn't guaranteed, but it happens a lot!
