### ISSUE TITLE
Error due to null value

### ISSUE THREAD

**Issue by KlierWang** [ashphy/jsonpath-online-evaluator#73]
Demo

`
$.[?(@.id==='1')]
`

Error:
jsonPath: Cannot read properties of null (reading 'id'): _$_v.id==='1'
`[{
    "id": null,
    "name": "test"
}]`

Success:
`[{
    "id": "1",
    "name": "test"
}]
`

**Comment by KlierWang** [comment]
?????

**Comment by ashphy** [comment]
Use a template instead.
