### ISSUE TITLE
json2html?

### ISSUE THREAD

**Issue by stokebreakup** [ashphy/jsonpath-online-evaluator#74]
**This project uses a [JSONPath-Plus](https://github.com/JSONPath-Plus/JSONPath) as a jsonpath parser. For the parser issues, please report to the JSONPath repository.**

**Describe the bug**
```json5
{"<>": "li", "html":[
    	{"<>": "span", "text": "${name} (${age} years old)"}
      ]
    
}
```

**To Reproduce**
`$.html.["<>"]``

**Expected behavior**
I'm trying to make a jsonpath from json2html

**Screenshots**
![image](https://github.com/ashphy/jsonpath-online-evaluator/assets/165694895/38ed54e4-32fb-43bf-a6c0-c6db564d7a4c)

**Environment (please complete the following information):**
 - Browser [safari]
 - Version [last version]

**Additional context**
json2html is an open source javascript library that uses json templates to render JSON objects into HTML.

**Comment by ashphy** [comment]
Give **a clear and concise description of what the bug is**.

**Comment by ashphy** [comment]
It appears there may be a misunderstanding. This issue tracker is intended for bug reports and feature requests related to this project.

Regarding JSONPath, it is a separate library from json2html and not directly supported by this library. If you require this functionality, you may wish to consider implementing it yourself or searching for existing libraries that support JSONPath.

**Comment by ashphy** [comment]
I’m afraid I’m having trouble understanding the connection between JSONPath and json2html. JSONPath is a query language, and it seems unrelated to json2html. Additionally, this repository does not handle requests related to JSONPath specifications. It might be better to direct your request to a more appropriate forum.
