### ISSUE TITLE
$..['type'][?(@ == 'home')] yields no results

### ISSUE THREAD

**Issue by RedX2501** [ashphy/jsonpath-online-evaluator#9]
The expression `$..['type'][?(@ == 'home')]` does not seem to yield any results yet `$..[?(@['type'] == 'home')]` does.

Is that a bug?

**Comment by ashphy** [comment]
This site uses JSONPath Plus(https://github.com/s3u/JSONPath) as a parser. JSONPath has no standard specifications. So your direct feedback to the library will improve the quality.
